---
# tasks file for programes
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instal·lar programes de desenvolupament
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ desenvolupament }}"

- name: Instal·lar programes de SMX
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ smx }}"
