---
- hosts: xinxan.local
  user: pi

  vars:
    programa:
      - joe
      - htop

  tasks:
    - name: Comprovar que està viu
      ping:

    - name: Instal·lar {{programa}}
      apt: name={{programa}} state=present
      become: yes
