---
# file: installa_alumnes.yml
#
# Instal·lació dels ordinadors de mostra dels alumnes
#
#    - Cada un dels roles permeten fer instal·lacions
#      d'alguna cosa concreta
#    - s'ha d'executar amb --ask-vault-pass o --vault-password-file
#
#    TODO:
#    - Segurament s'hauria de fer algun tipus de variable
#      global per les configuracions que es desitgen?
#
# Versió 1: 12/8/2016
#    Encara no fa la configuració LDAP
#
# Versió 1.01: 14/8/2016
#    Ja funciona la configuració LDAP però requereix
#    tenir els grups vboxusers i docker o no deixa
#    fer login gràficament...
#
- hosts: alumnes
  user: usuari
  become: true

  roles:
    - common
    - { role: alumne-config, tags: alumne-config }
    - { role: programes, tags: programes }
    - { role: chrome, tags: chrome }
    - { role: virtualbox, tags: virtualbox }
    - { role: java, tags: java }
    - { role: netcore }
    - { role: docker, tags: docker }
    - { role: atom, tags: editors }
    - { role: vscode, tags: editors }
    - { role: brackets, tags: editors }
    - { role: packet-tracer, tags: packet-tracer }
    - {
        role: openldap_client,
        ldap_config:
          {
            base: "dc=cendrinf,dc=ies",
            uri: "ldap://192.168.4.11",
            rootbinddn: "cn={{ ldap_user }},dc=cendrinf,dc=ies",
            port: 389,
            secret: "{{ ldap_password }}",
          },
        tags: openldap_client,
      }
    - { role: grub-config }
