galaxy_info:
  author: Xavier Sala
  description: Genera la configuració LDAP del servidor
  company: Institut Cendrassos

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

dependencies:
  - role: openldap_server
