---
# Descarregar i instal·lar vscode
- name: Descarregar Visual Studio Code
  get_url:
    url: "{{ vscode_url_deb }}"
    dest: "{{ vscode_tmp_deb }}"
    force: yes

- name: Installar Visual Studio Code
  apt:
    deb: "{{ vscode_tmp_deb }}"
