---
# Check virtualbox and extpack versions

- name: Comprova la versió de VirtualBox
  shell: "VBoxManage --version | cut -d 'r' -f 1"
  register: virtualbox_version

- name: Comprova si l'extension pack ja hi és
  shell: "vboxmanage list extpacks | grep 'Version:' | cut -d ':' -f 2 | xargs"
  register: extpack_version

- name: Acaba si ja estem en la versió correcta
  meta: end_play
  when: "extpack_version.stdout == virtualbox_version.stdout"

- name: Descarregar VirtualBox extension pack
  shell: "cd /tmp/ &&  wget http://download.virtualbox.org/virtualbox/{{virtualbox_version.stdout}}/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_version.stdout}}.vbox-extpack"

- name: Instal·lar VirtualBox extension pack
  shell: "echo 'y' | VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_version.stdout}}.vbox-extpack"
