---
# tasks file for chrome
- name: Afegir la clau pública de Google
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Afegir repositori de Google Chrome
  apt_repository:
    repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    update_cache: yes
    state: present

- name: Instal·lar Google Chrome
  apt:
    pkg: google-chrome-stable
    state: present
