#
# Actualització dels ordinadors de la xarxa
#
#    TODO:
#
# Versió 1: 14/8/2016
#     Primera versió
# Versió 2:  1/9/2017
#     Canviada l'actualització a roles
#     Sembla que el vscode afegeix el repositori automàticament
# Versió 3:
#     Actualització de guest additions de VirtualBox
#
- hosts: all
  user: usuari
  become: true
  roles:
    - system-upgrade
    - { role: atom }
    - { role: virtualbox-update }
