---
# Canvia el hostname a partir del nom que se li dóna en l'inventari
#
# La idea és tenir un inventari amb nom i IP:
#
#  [alumnes]
#     i310-04d ansible_ssh_host=192.168.10.32
#     i310-04e ansible_ssh_host=192.168.10.30
#     i310-04m ansible_ssh_host=192.168.10.31
#
#  Al host se li assignarà el nom definit en l'inventari (en l'exemple
#  seria 'i310-04..' )
#

- hosts: all
  user: usuari
  become: yes

  tasks:
    - name: Afegeix el nom a /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1   {{ inventory_hostname }} {{ansible_hostname}}"
        owner: root
        group: root
        mode: 0644
      when: "inventory_hostname != ansible_hostname"

    - name: Canvia el hostname
      hostname: name="{{ inventory_hostname }}"
      when: "inventory_hostname != ansible_hostname"
      notify:
        - Reinicia
        - Espera que estigui en marxa

  handlers:
    # - name: Reinicia
    #   reboot:
    #     reboot_timeout: 3600
    #   register: resultat
    #   notify:
    #     - informa

    # - name: informa
    #   debug:
    #     msg: "{{ inventory_hostname }} reiniciat en {{ resultat.elapsed }}"

    - name: Reinicia
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Espera que estigui en marxa
      wait_for_connection:
        delay: 60
        timeout: 300
# - name: Espera que reinicii
#   local_action:
#     module: wait_for
#       host="{{ inventory_hostname }}"
#       port=22 state=started
#     become: false
